export const SET_DATA = 'SET_DATA';
export const ADD_ARTICLE = 'ADD_ARTICLE';
export const DATA_LOADED = 'DATA_LOADED';
export const DATA_REQUESTED = 'DATA_REQUESTED';
export const SAVE_COURSE = 'SAVE_COURSE';

export const SUCCESSFULL_AUTHENTICACION = 'SUCCESSFULL_AUTHENTICACION';
export const FAILED_AUTHENTICATION = 'FAILED_AUTHENTICATION';

export const SUCCESSFULL_NEW_COURSE='SUCCESSFULL_NEW_COURSE';
export const FAILED_NEW_COURSE='FAILED_NEW_COURSE';

export const SUCCESSFULL_ACTIVE_USER="SUCCESSFULL_ACTIVE_USER";

export const STUDENT_LIST="STUDENT_LIST";
export const SHOW_PROGRAMMBS="SHOW_PROGRAMMBS";
export const UPDATE_REVISION_PROGRAMMBS="UPDATE_REVISION_PROGRAMMBS";
export const SHOW_USER="UPDATE_REVISION_PROGRAMMBS";

export const UPDATE_LANGUAGE_SELECT="UPDATE_LANGUAGE_SELECT";
export const UPDATE_COUNTRY_SELECT="UPDATE_LANGUAGE_SELECT";
export const LOAD_FORM_PROGRAMMBS="LOAD_FORM_PROGRAMMBS";
export const LOAD_FORM_STUDENT="LOAD_FORM_STUDENT";

export const LOAD_FORM_USER="LOAD_FORM_USER";
export const EDIT_USER="EDIT_USER";
export const SUCCESSFULL_EDIT_USER="SUCCESSFULL_EDIT_USER";
export const ERROR_EDIT_USER="ERROR_EDIT_USER";
export const ERROR_REQUIRE_FIELDS="ERROR_REQUIRE_FIELDS";
export const COUNTRY_LIST="COUNTRY_LIST";



