export const SET_DATA = 'SET_DATA';
export const ADD_ARTICLE = 'ADD_ARTICLE';
export const DATA_LOADED = 'DATA_LOADED';
export const DATA_REQUESTED = 'DATA_REQUESTED';
 
// Authentication Constants 
export const SUCCESSFULL_AUTHENTICATION = 'SUCCESSFULL_AUTHENTICATION';
export const FAILED_AUTHENTICATION = 'FAILED_AUTHENTICATION';

// Constants of Course
export const SUCCESSFULL_NEW_COURSE='SUCCESSFULL_NEW_COURSE';
export const FAILED_NEW_COURSE='FAILED_NEW_COURSE';
export const SAVE_COURSE = 'SAVE_COURSE';

// Constants of Programmbs
export const SHOW_PROGRAMMBS="SHOW_PROGRAMMBS";
export const UPDATE_REVISION_PROGRAMMBS="UPDATE_REVISION_PROGRAMMBS";
export const LOAD_FORM_PROGRAMMBS="LOAD_FORM_PROGRAMMBS";

// Constants of Student
export const STUDENT_LIST="STUDENT_LIST";
export const SHOW_STUDENT="SHOW_STUDENT";
export const LOAD_FORM_STUDENT="LOAD_FORM_STUDENT";
export const EDIT_STUDENT="EDIT_STUDENT";
export const ERROR_EDIT_STUDENT="ERROR_EDIT_STUDENT";
export const DELETE_STUDENT="DELETE_STUDENT";
export const EDIT_PASSWORD_STUDENT="EDIT_PASSWORD_STUDENT"

// Constants of User
export const SHOW_USER="SHOW_USER";
export const LOAD_FORM_USER="LOAD_FORM_USER";
export const EDIT_USER="EDIT_USER";
export const DELETE_USER="DELETE_USER";
export const EDIT_PASSWORD_USER="EDIT_PASSWORD_USER";
export const ERROR_EDIT_USER="ERROR_EDIT_USER";
export const SUCCESSFULL_ACTIVE_USER="SUCCESSFULL_ACTIVE_USER";

// General Constants 
export const SUCCESSFULL_EDIT="SUCCESSFULL_EDIT";
export const SUCCESSFUL_DELETE="SUCCESSFUL_DELETE";
export const ERROR_REQUIRED_FIELDS="ERROR_REQUIRED_FIELDS";
export const SUCCESS_REQUIRED_FIELDS="SUCCESS_REQUIRED_FIELDS";
export const COUNTRY_LIST="COUNTRY_LIST";

// Select Constans 
export const UPDATE_LANGUAGE_SELECT="UPDATE_LANGUAGE_SELECT";
export const UPDATE_PROGRAM_SELECT="UPDATE_PROGRAM_SELECT";
export const UPDATE_MODALITY_SELECT="UPDATE_MODALITY_SELECT";
export const UPDATE_COUNTRY_SELECT="UPDATE_COUNTRY_SELECT";

// Constants of Group
export const GROUP_LIST="GROUP_LIST"
export const LOAD_FORM_GROUP="LOAD_FORM_GROUP";
export const SHOW_GROUP="SHOW_GROUP"
export const EDIT_GROUP="EDIT_GROUP"

